import type { NextPage } from "next";
import Head from "next/head";
import { createContext, useEffect, useState } from "react";
import { Account, Data } from "../core/types";
import HomeView from "../views/home";

export const AccountContext = createContext<Account>(
  null as unknown as Account
);

const Home: NextPage = () => {
  const fetchData = async () => {
    const data = await fetch("./data.json", {
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    }).then((res) => res.json().then((data: Data) => data));

    return data;
  };

  const [data, setData] = useState<Data>();

  useEffect(() => {
    fetchData().then((data) => setData(data));
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {data && (
        <AccountContext.Provider value={data.account}>
          <HomeView
            totalSales={data.totalSales}
            newQuote={data.newQuote}
            orders={data.orders}
            products={data.products}
            visitorsGraph={data.visitorsGraph}
            weeklySalesAndExpense={data.weeklySalesAndExpense}
            totalChargeAndProfit={data.totalChargeAndProfit}
            customerRatings={data.customerRatings}
            votes={data.votes}
            websiteTraffic={data.websiteTraffic}
            pieText={data.pieText}
            profileInfo={data.profileInfo}
          />
        </AccountContext.Provider>
      )}
    </div>
  );
};

export default Home;
